package backend;

import flixel.input.keyboard.FlxKey;

class KeyNames {
    public static final keyMap:Map<FlxKey, String> = [
        A         => "A",
        B         => "B",
        C         => "C",
        D         => "D",
        E         => "E",
        F         => "F",
        G         => "G",
        H         => "H",
        I         => "I",
        J         => "J",
        K         => "K",
        L         => "L",
        M         => "M",
        N         => "N",
        O         => "O",
        P         => "P",
        Q         => "Q",
        R         => "R",
        S         => "S",
        T         => "T",
        U         => "U",
        V         => "V",
        W         => "W",
        X         => "X",
        Y         => "Y",
        Z         => "Z",
        ZERO      => "0",
        ONE       => "1",
        TWO       => "2",
        THREE     => "3",
        FOUR      => "4",
        FIVE      => "5",
        SIX       => "6",
        SEVEN     => "7",
        EIGHT     => "8",
        NINE      => "9",
        UP        => "Up",
        DOWN      => "Down",
        LEFT      => "Left",
        RIGHT     => "Right",
        SPACE     => "Space",
        ENTER     => "Enter",
        ESCAPE    => "Esc",
        BACKSPACE => "Backspace",
        TAB       => "Tab",
        CONTROL   => "Ctrl",
        ALT       => "Alt",
        SHIFT     => "Shift",
        PLUS      => "+",
        MINUS     => "-",
        PERIOD    => ".",
        COMMA     => ",",
        SEMICOLON => ";",
        QUOTE     => "'",
        LBRACKET  => "[",
        RBRACKET  => "]",
        BACKSLASH => "\\",
        SLASH     => "/",
        GRAVEACCENT => "`",
        CAPSLOCK  => "Caps Lock",
        PAGEUP    => "Page Up",
        PAGEDOWN  => "Page Down",
        HOME      => "Home",
        END       => "End",
        INSERT    => "Insert",
        DELETE    => "Delete",
        F1        => "F1",
        F2        => "F2",
        F3        => "F3",
        F4        => "F4",
        F5        => "F5",
        F6        => "F6",
        F7        => "F7",
        F8        => "F8",
        F9        => "F9",
        F10       => "F10",
        F11       => "F11",
        F12       => "F12"
    ];

    public static function getKeyName(key:FlxKey):String {
        return key == NONE ? "-" : (keyMap.exists(key) ? keyMap[key] : '($key)');
    }

    public static function keysToString(keys:Array<FlxKey>):String {
        return keys.map(k -> getKeyName(k)).join(", ");
    }
}